[Feature]  SearchPage 생성
dh413/ThankYouFront2 pull request #12
Opened 2024-06-03 02:47 UTC by dh413

## 어떤 이유로 PR을 하셨나요?
 * [x]  feature 병합
 * [ ]  버그 수정
 * [ ]  코드 개선
 * [ ]  기타(아래에 자세한 내용을 기입해주세요)
 
 ## 스크린샷 및 세부 내용 - 왜 해당 PR이 필요한지 자세하게 설명해주세요
![image](https://github.com/dh413/ThankYouFront2/assets/148740246/66547e05-6ef1-4476-a874-ea2a07e7cad1)

SearchLayout의 각 항목 생성 , 동적페이지 사용

2024-06-03 03:03 UTC, dh413 commented
const SELECT_URL = "/search/" + params.pagename;

 상수화 추가 작업했습니다.
  const SELECT_URL = APP_ROUTES.URL.SEARCH + "/" + params.pagename;

2024-06-03 03:07 UTC, daehyeongLee-aladin commented on src/app/(web)/search/[pagename]/page.tsx
> +  const SELECT_URL = "/search/" + params.pagename;
/search 이것도 상수로 따로 빼면 좋을 거 같습니다!

2024-06-03 03:07 UTC, daehyeongLee-aladin commented on src/app/(web)/search/layout.tsx
> +      <SearchNavigation></SearchNavigation>
chlidren 없으면 self-closing 해주세요

2024-06-03 03:07 UTC, daehyeongLee-aladin commented on src/components/search/SearchNavigation.tsx
> +"use Client";
client 대분자로 들어가있네요

2024-06-03 03:07 UTC, daehyeongLee-aladin commented on src/components/Navigation.tsx
> +          {MAIN_NAVIGATION_ITEMS.map((item, index) => {
여기 index는 사용하나요?

2024-06-03 04:57 UTC, dh413 commented on src/app/(web)/search/[pagename]/page.tsx
> +  const SELECT_URL = "/search/" + params.pagename;
처리했습니다~

2024-06-03 04:57 UTC, dh413 commented on src/app/(web)/search/layout.tsx
> +      <SearchNavigation></SearchNavigation>
처리했습니다~

2024-06-03 04:57 UTC, dh413 commented on src/components/search/SearchNavigation.tsx
> +"use Client";
처리했습니다~

2024-06-03 04:58 UTC, dh413 commented on src/components/Navigation.tsx
> +          {MAIN_NAVIGATION_ITEMS.map((item, index) => {
처리했습니다~

2024-06-03 05:05 UTC, aladin-subin requested changes
PR 올리실 때 설명 더 상세히 적어주세요.
동적 페이징을 왜 사용했는지에 대한 설명이 더 있으면 좋겠습니다.

2024-06-03 05:05 UTC, aladin-subin commented on src/app/(web)/search/[pagename]/page.tsx
> +      {SELECT_URL === SEARCH_ROUTES.URL.BRAND && <Brand />}
각 페이지별로 기능, 필터가 모두 많이 다르기 때문에 동적 라우팅을 사용하기엔 적절하지 않은 것 같습니다!

2024-06-03 05:06 UTC, aladin-subin requested changes

2024-06-03 05:06 UTC, aladin-subin commented on src/app/(web)/search/[pagename]/page.tsx
> +  const SELECT_URL = APP_ROUTES.URL.SEARCH + "/" + params.pagename;
usePathname 사용하면 될 것 같습니다.

2024-06-04 00:08 UTC, aladin-subin approved these changes
수고하셨습니다.
설명 상세히 변경해주세요

2024-06-04 00:11 UTC, daehyeongLee-aladin approved these changes

2024-06-04 00:15 UTC, merged