WIP[Feature] 검색결과 기능 추가
dh413/ThankYouFront2 pull request #18
Opened 2024-06-04 07:27 UTC by dh413

## 어떤 이유로 PR을 하셨나요?
 * [x]  feature 병합
 * [ ]  버그 수정
 * [ ]  코드 개선
 * [ ]  기타(아래에 자세한 내용을 기입해주세요)
 
 ## 스크린샷 및 세부 내용 - 왜 해당 PR이 필요한지 자세하게 설명해주세요
![image](https://github.com/dh413/ThankYouFront2/assets/148740246/58debe79-07d7-4bcd-9b45-2a8b7bd692e1)

1. src/app/(web)/item/page.tsx 페이지의 
컴포넌트 구조 가 맞는지 궁금합니다.

<SearchText> -텍스트검색
<ItemFilter> - 필터
<ItemResult> - 결과
<ItemFooter> - footer
item/page.tsx에서 각각의 컴포넌트가 들어가 있어야 한다고 생각했습니다.

2024-06-04 08:40 UTC, daehyeongLee-aladin commented on src/app/(web)/search/item/page.tsx
> +  const [resultViewState, setResultViewState] = useState<boolean>(false);
boolean 타입이면 네이밍 앞이 is 나 has 이면 좋습니다.

2024-06-04 08:40 UTC, daehyeongLee-aladin commented on src/components/Navigation.tsx
> +        setOperatorCode(userObject.operatorCode);
error일 때 특별한 처리가 없다면 그냥 userObject.operatorCode가 truly할때만 아래 코드가 실행되게 하는 게 나을 거 같습니다!

2024-06-04 08:40 UTC, daehyeongLee-aladin commented on src/components/search/Item/ItemResult.tsx
> +        <div className="col-12">
col이 하나밖에 없는 거 같아서 row와 col을 불필요하게 겹쳐질 수도 있을 거 같은데, 겹쳐진 div 태그를 줄일 수 있는 방향을 고민해보시는 것도 좋을 거 같습니다.

2024-06-04 08:40 UTC, daehyeongLee-aladin commented on src/hooks/search/item/useGetSearchItem.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
여기도 boolean 타입이면 is나 has을 네이밍 앞에 붙여주면 좋을 거 같습니다.

2024-06-04 08:52 UTC, dh413 commented on src/app/(web)/search/item/page.tsx
> +  const [resultViewState, setResultViewState] = useState<boolean>(false);
넵! 앞으로 그렇게 작성할께요

2024-06-04 08:55 UTC, dh413 commented on src/components/Navigation.tsx
> +        setOperatorCode(userObject.operatorCode);
조건절로 처리했습니다~

2024-06-04 08:56 UTC, aladin-subin requested changes
1. page에 컴포넌트를 넣는게 일반적인지
컴포넌트 안에 컴포넌트를 넣는게 일반적인지 궁금합니다. ex) 검색어컴포넌트안에 filter컴포넌트를 사용
**→ 둘 다 상관 없습니다.**

2. useSearchParams 를 사용해서 한번에 받아서 처리할 순 없는지.. param.get() 너무 많이 반복
**→ 값을 받아서 새 변수에 할당하는 형식이므로 일일이 가져오는게 맞습니다.**

3. 무한 API호출을 하게 되어 useMemo를 사용하여 처리하였는데 다른방법이 있는지?
**→ useEffect 내의 dependency가 잘못되었을 확률이 큽니다. 확인해보세요.**

2024-06-04 08:56 UTC, aladin-subin commented on src/app/(web)/search/item/page.tsx
> +  const [resultViewState, setResultViewState] = useState<boolean>(false);
[boolean 네이밍](https://frogand.tistory.com/211) 확인 후 변경 부탁드립니다

2024-06-04 08:56 UTC, aladin-subin commented on src/hooks/search/item/useGetSearchItem.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
[boolean 네이밍 방법](https://frogand.tistory.com/211) 확인 후 변경 부탁드립니다

2024-06-04 08:56 UTC, aladin-subin commented on src/components/search/Item/ItemResult.tsx
> +      isDirectDelivery: isDirectDelivery,
object의 key와 value가 같다면 한번만 사용하셔도 무방합니다. [링크](https://pro-self-studier.tistory.com/33) 참고해주세요

2024-06-04 08:56 UTC, aladin-subin commented on src/hooks/search/item/useGetSearchItem.tsx
> +const useGetSearchItem = (searchData: any) => {
검색 목록을 불러오는 것 같은데 Item은 어색하다고 느껴집니다.

any 사용은 지양해주세요.

2024-06-04 08:58 UTC, aladin-subin requested changes
추가로, user 정보 전부를 cookie에 저장하는 방식인 것 같은데, 이는 보안상 취약할 수 있습니다.
쿠키에 개인정보를 담지 말아주세요.

2024-06-04 12:04 UTC, dh413 commented on src/hooks/search/item/useGetSearchItem.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
const [isResultView, setIsResultView] = useState<boolean>(false); 로 처리했습니다.

2024-06-04 12:06 UTC, dh413 commented on src/app/(web)/search/item/page.tsx
> +  const [resultViewState, setResultViewState] = useState<boolean>(false);
const [isResultView, setIsResultView] = useState(false); 로 처리했습니다.

2024-06-04 12:06 UTC, dh413 commented on src/hooks/search/item/useGetSearchItem.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
const [isLoading, setIsLoading] = useState<boolean>(true); 로 처리했습니다.

2024-06-04 12:06 UTC, dh413 commented on src/hooks/search/item/useGetSearchItem.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
const [isLoading, setIsLoading] = useState(true); 로 처리했습니다.

2024-06-04 12:07 UTC, dh413 commented on src/app/(web)/search/item/page.tsx
> +  const [resultViewState, setResultViewState] = useState<boolean>(false);
const [isResultView, setIsResultView] = useState(false); 로 처리했습니다.

2024-06-04 12:09 UTC, dh413 commented on src/components/search/Item/ItemResult.tsx
> +      isDirectDelivery: isDirectDelivery,
단축 속성명(ES6) 몰랐네요 숙지하겠습니다~

2024-06-04 12:20 UTC, dh413 commented on src/hooks/search/item/useGetSearchItem.tsx
> +const useGetSearchItem = (searchData: any) => {
useGetSearchResults 으로 변경
searchData type 생성했습니다.

2024-06-05 00:09 UTC, daehyeongLee-aladin commented on src/components/login/LoginForm.tsx
> +
여기 빈칸이 또 들어갔네요. 올리시기 전이나 후에 diff를 재확인하는 게 좋을 거 같습니다.

2024-06-05 00:18 UTC, aladin-subin requested changes

2024-06-05 00:18 UTC, aladin-subin commented on package.json
> +    "typescript": "5.4.5"
지난번에도 말씀드렸듯 버전 변경은 협의 없이 이루어지면 안됩니다.
현재는 과제이니 괜찮지만, 실제 프로덕트에서는 협의 없이는 진행되면 안돼요!

2024-06-05 00:18 UTC, aladin-subin commented on src/app/(web)/search/item/page.tsx
> +  const [isResultView, setIsResultView] = useState<boolean>(false);
검색 결과가 있으면 보여주고 없으면 안보여주는 것에 대한 bool값이라면 hasResult가 좀 더 적합할 것 같습니다.

2024-06-05 00:18 UTC, aladin-subin commented on src/hooks/search/item/useGetSearchResults.tsx
> +
이러한 빈칸은 lint로 처리해주세요.
저장 시 lint가 잘 동작하는지 확인해주시고 ide에 autosave 기능도 켜주시면 좋을 것 같습니다

2024-06-05 00:18 UTC, aladin-subin commented on src/hooks/search/item/useGetSearchResults.tsx
> +    };
이 함수는 useEffect 바깥으로 빼는 것이 좋을 것 같습니다

2024-06-05 00:18 UTC, aladin-subin commented on src/hooks/search/item/useGetSearchResults.tsx
> +const useGetSearchResults = (searchData:SearchData) => {
`searchData:SearchData` 와 같이 띄어쓰기가 이루어지지 않는 것으로 보아 lint 제대로 동작하지 않는 것 같습니다.

2024-06-05 00:18 UTC, aladin-subin commented on src/types/search/common/type.ts
> +}
type에 null은 왜 들어간걸까요?

2024-06-05 01:18 UTC, dh413 commented on src/components/login/LoginForm.tsx
> +
집에서 세팅 다시 하겠습니다~

2024-06-05 01:20 UTC, dh413 commented on src/hooks/search/item/useGetSearchResults.tsx
> +
넵 세팅 다시해놓겠습니다

2024-06-05 01:20 UTC, dh413 commented on src/app/(web)/search/item/page.tsx
> +  const [isResultView, setIsResultView] = useState<boolean>(false);
hasResult 로 변경하였습니다

2024-06-05 01:23 UTC, dh413 commented on src/types/search/common/type.ts
> +}
검색할때 값이 해당 type이 없을 수도 있어서 null처리도 해놨습니다.

2024-06-05 01:24 UTC, dh413 commented on src/types/search/common/type.ts
> +}
export interface SearchData {
  searchType?: string;
  operatorCode: string;
  sortOrder?: string;
  branchType?: string;
  includeOutOfStock?: string;
  mdLevel?: string;
  isDirectDelivery?: string;
}
로 변경했습니다.

2024-06-05 01:26 UTC, dh413 commented on package.json
> +    "typescript": "5.4.5"
네 알겠습니다!

2024-06-05 02:03 UTC, dh413 commented on src/types/search/common/type.ts
> +}
useSearchParam에 null이 들어갈 수 있기 때문에 에러가 나서 type에 null 조건을 넣었는데요

![image](https://github.com/dh413/ThankYouFront2/assets/148740246/b955c9c6-41f7-4a0b-96dd-cf9bc029d862)
이렇게 변경하고 type의 null조건 뺐습니다!

2024-06-05 03:10 UTC, aladin-subin approved these changes
수고하셨습니다

2024-06-05 03:10 UTC, aladin-subin commented on src/components/search/Item/ItemMain.tsx
> +    const mdLevel = params.get(SEARCH.MD_LEVEL) ?? "";
밖으로 빼는게 좋을 것 같은데, useEffect 안에 넣은 이유가 있으실까요?

2024-06-05 03:26 UTC, dh413 commented on src/components/search/Item/ItemMain.tsx
> +    const mdLevel = params.get(SEARCH.MD_LEVEL) ?? "";
useEffect안에서만 사용하려고 넣었습니다 
keyword, searchType, includeOutOfStock 등 
다른 컴포넌트에서 동일하게 변수명으로 사용하고 있어서 그랬습니다 
만약 다른 컴포넌트에서 동일한 변수명으로 반복적으로 사용하고 있을 때는 어떻게 처리하시나요?

2024-06-05 04:40 UTC, daehyeongLee-aladin approved these changes
수고하셨습니다~

2024-06-05 04:43 UTC, merged