[Feature] ClientLayout 추
dh413/ThankYouFront2 pull request #4
Opened 2024-05-29 02:42 UTC by dh413

> ## 어떤 이유로 PR을 하셨나요?
> * [x]  feature 병합
> * [ ]  버그 수정
> * [ ]  코드 개선
> * [ ]  기타(아래에 자세한 내용을 기입해주세요)
> 
> ## 스크린샷 및 세부 내용 - 왜 해당 PR이 필요한지 자세하게 설명해주세요
> RootLayout clientLayout 분리 
> /(web)/layout.tsx 에 Recoil을 사용하려고 함 
> Recoil 클라이언트 컴포넌트라 RootLayout에 사용 x

2024-05-29 07:35 UTC, aladin-subin requested changes
보통 app 디렉토리 아래에는 page 관련된 부분만 있습니다.
components는 app 디렉토리 바깥에 위치하도록 수정해주세요.

2024-05-29 07:35 UTC, aladin-subin commented on src/app/(web)/layout.tsx
> +import ClientLayout from "./layouts/ClientLayout";
P2: 절대경로 사용해주세요.
절대경로를 사용해야하는 이유에 대해 고민 후 답변 달아주시면 좋을 것 같습니다!

2024-05-29 07:35 UTC, aladin-subin commented on src/app/(web)/layouts/ClientLayout.tsx
> +export default function ClientLayout({
P2: client layout 보단 좀 더 명시적인 이름으로 지어주시면 좋을 것 같습니다.

2024-05-29 08:47 UTC, dh413 commented on src/app/(web)/layout.tsx
> +import ClientLayout from "./layouts/ClientLayout";
1. import문이 길어진다 ../../../
2. 해당 페이지가 이동했을 경우 상대 경로라 에러가 발생한다

2024-05-29 08:50 UTC, dh413 commented on src/app/(web)/layouts/ClientLayout.tsx
> +export default function ClientLayout({
CommonLayout 로 변경하였습니다.

2024-05-29 08:50 UTC, aladin-subin commented on src/app/(web)/layout.tsx
> +import ClientLayout from "./layouts/ClientLayout";
좋습니다 👍  앞으로의 모든 코드에서는 절대 경로를 사용해주세요!!

2024-05-30 00:01 UTC, aladin-subin requested changes

2024-05-30 00:01 UTC, aladin-subin commented on package.json
> +    "next": "^14.2.3",
실제 서비스에선 버전 변경도 웬만하면 하지 않는게 좋습니다!

2024-05-30 00:01 UTC, aladin-subin commented on src/components/Navigation.tsx
> +    window.location.href = "/login";
redirect 하는 다른 방법이 있습니다. 변경해주세요

2024-05-30 01:06 UTC, dh413 commented on src/components/Navigation.tsx
> +    window.location.href = "/login";
router.push("/login"); 로 처리했습니다!

2024-05-30 01:06 UTC, dh413 commented on package.json
> +    "next": "^14.2.3",
넵! 집에서 새로 install하면서 생긴 것 같습니다~ 
주의하겠습니다

2024-05-30 01:09 UTC, aladin-subin requested changes

2024-05-30 01:09 UTC, aladin-subin commented on src/components/Navigation.tsx
>      Cookies.remove("user");
쿠키 key값 상수화 해주세요

2024-05-30 01:09 UTC, aladin-subin commented on src/components/Navigation.tsx
> +    router.push("/login");
path 상수화 해주세요!

대홍님 PR에서 언급드린 내용은 다른 PR에서도 똑같이 유념하셔야할 부분입니다!
잘 신경써서 해주시면 좋을 것 같습니다!

2024-05-30 05:56 UTC, aladin-subin requested changes
eslint, prettier 적용해주세요!

2024-05-30 05:56 UTC, aladin-subin commented on src/components/Navigation.tsx
> +        onClick: "handleLogout",
동작하나요...???

2024-05-30 05:56 UTC, aladin-subin commented on src/constants/cookie.ts
> +export const COOKIE_NAME = "user";
확장성을 고려해서 작성하시면 좋을 것 같습니다.
user 정보 외에 쿠키가 사용될 수도 있다는 것을 고려하면 어떤 식으로 바꾸는게 좋을까요?

2024-05-30 05:56 UTC, aladin-subin commented on src/constants/routes.ts
> +  const NEXT_PUBLIC_API_URL = "https://tkapi.aladin.co.kr";
.env 에 넣어주세요

2024-05-30 05:56 UTC, aladin-subin commented on src/components/login/LoginForm.tsx
> +              //443연결 되면 주석해제
이러한 주석에는 TODO 달아놓으면 좋을 것 같습니다.

2024-05-30 05:56 UTC, aladin-subin commented on src/components/login/LoginForm.tsx
>              setloginInfo(result.data);
카멜케이스에 맞게 변경해주세요

2024-05-30 05:56 UTC, aladin-subin commented on src/components/Navigation.tsx
> +  const LOGIN_CHECK_NAV_ITEMS = isLoggedIn
배열이 아닌데 ITEMS라고 하는게 어색하게 느껴집니다

2024-05-30 05:56 UTC, aladin-subin commented on src/components/Navigation.tsx
> +                  : undefined
이렇게 해도 가능은 한데 저라면 다른 방식으로 작성할 것 같습니다.
고민해보시겠어요?!

2024-05-30 05:59 UTC, aladin-subin commented on src/constants/routes.ts
> +export const MAIN_NAV_ITEMS = [
타입 따로 정의해주시면 좋을 것 같습니다.
LOGIN_CHECK_NAV_ITEMS 에서도 동일한 타입인 것 같으니, 따로 타입 정의해주시는게 좋을 것 같아요~

2024-05-30 06:09 UTC, daehyeongLee-aladin commented on src/components/Navigation.tsx
> +            }`;
위 조건들이 모두 false일 경우 className에 불필요한 공백이 많이 들어갈 것처럼 보입니다!

2024-05-30 06:09 UTC, daehyeongLee-aladin commented on src/components/Navigation.tsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(false);
타입이 빠졌습니다~

2024-05-30 08:38 UTC, dh413 commented on src/components/Navigation.tsx
> +                  : undefined
동적클래스네임 classNames 해서 처리했습니다! 
만약에 다른 방식이면 알려주세요!!

2024-05-30 08:39 UTC, aladin-subin requested changes

2024-05-30 08:39 UTC, aladin-subin commented on src/components/Navigation.tsx
> +                key={index}
key값으로 index를 사용하면 안되는 이유에 대해 찾아보시고, 수정 부탁드려요~!

2024-05-30 08:39 UTC, aladin-subin commented on src/types/common/app.ts
> +export interface NavList {
Navigation 한 항목에 대한 타입이고, 이를 NavList[] 라고 사용할텐데, 이는 어색하다고 느껴집니다. 변경해주세요.

2024-05-30 08:42 UTC, aladin-subin requested changes

2024-05-30 08:42 UTC, aladin-subin commented on src/components/Navigation.tsx
> +        onClick: "handleLogout",
저라면 그냥 `onClick: handleLogout` 으로 함수 자체를 넣고, 
아래의 onClick에서
`onClick={LOGIN_CHECK_NAV_ITEM?.onClick ?? undefined}` 와 같이 사용할 것 같습니다.

2024-05-30 08:42 UTC, dh413 commented on src/components/Navigation.tsx
> +            }`;
classNames사용해서 처리했습니다.

2024-05-30 08:59 UTC, dh413 commented on src/components/Navigation.tsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(false);
처리했습니다 useState<boolean>

2024-05-31 00:24 UTC, dh413 commented on src/types/common/app.ts
> +export interface NavList {
NavList -> NavInfo 인터페이스명 변경했습니다.

2024-05-31 00:27 UTC, dh413 commented on src/components/Navigation.tsx
> +                key={index}
순서가 바뀔 수 있는 경우 key에 인덱스를 사용하는 것을 권장하지 않는다고 합니다.
layout의 title은 삭제가 없기 때문에 문제 없을 것 같긴 한데요

안정적인 고유성을 부여하기 위해 key를 item.url로 처리했습니다~

2024-05-31 00:50 UTC, dh413 commented on src/constants/cookie.ts
> +export const COOKIE_NAME = "user";
UseCookieKey 생성하였습니다 
기존 COOKIE_NAME등 상수화 삭제하였습니다 
이유는 쿠키별로 조건이 다를 수 있어 상수화가 필요 없을 것이라 판단했습니다~

2024-05-31 01:33 UTC, dh413 commented on src/components/Navigation.tsx
> +            }`;
linkClassName 배열을 
.filter(Boolean).join(" ") 으로 처리했습니다~
filter(Boolean) -> 공백 제거
join(" ") -> 배열의 각 값을 공백 넣고 합칩니다.

2024-05-31 05:11 UTC, aladin-subin requested changes
커밋메세지 작성 시 컨벤션에 따라주세요!
`[Feature]` 가 아닌 `Feat:` 입니다~

2024-05-31 05:11 UTC, aladin-subin commented on src/components/login/LoginForm.tsx
>            }
else문 사용하지 않는다면 제거해주세요

2024-05-31 05:11 UTC, aladin-subin commented on src/types/common/api.ts
> +}
cookie config 타입이 api 파일에 있는건 어색하게 느껴집니다. 폴더링 다시 고민해주세요.

2024-05-31 05:11 UTC, aladin-subin commented on src/types/common/api.ts
> +}
사용하지 않는 것 같은데 추후에 사용할 계획이 있으신건가요? 아니시라면 실제 사용할 때 추가해주시면 좋을 것 같습니다~

2024-05-31 05:16 UTC, daehyeongLee-aladin commented on src/components/Navigation.tsx
> +              .filter(Boolean)
이 필터는 왜 들어간걸까요??

2024-05-31 05:24 UTC, dh413 commented on src/components/Navigation.tsx
> +              .filter(Boolean)
null 인걸 빼려고 넣었습니다

2024-05-31 05:24 UTC, dh413 commented on src/types/common/api.ts
> +}
넵 알겠습니다!

2024-05-31 05:34 UTC, daehyeongLee-aladin commented on src/components/Navigation.tsx
> +              .filter(Boolean)
이부분에서는 join, filter와 같이 조작하기보단
``nav-link ${path === APP_ROUTES.URL.EXIT ? "text-primary" : ""}${path === item.url ? " text-primary" : ""}``
위와 같은 모양으로 그냥 공백이 안생기게 template string으로 가는게 나아보입니다!

2024-05-31 06:39 UTC, dh413 commented on src/components/Navigation.tsx
> +              .filter(Boolean)
filter를 사용하기 위해서 배열로 만들어야 하니까 
template string이 더 좋다고 하신거죠?

template string으로 처리했습니다!

2024-05-31 06:46 UTC, dh413 commented on src/components/login/LoginForm.tsx
>            }
넵!

2024-05-31 06:46 UTC, dh413 commented on src/types/common/api.ts
> +}
넵 !

2024-05-31 07:09 UTC, aladin-subin approved these changes
수고하셨습니다~

2024-05-31 07:11 UTC, daehyeongLee-aladin approved these changes
수고하셨습니다~!

2024-05-31 07:22 UTC, merged