[Feature] Search Layout 추가
dh413/ThankYouFront2 pull request #5
Opened 2024-05-29 03:13 UTC by dh413

> ## 어떤 이유로 PR을 하셨나요?
> * [x]  feature 병합
> * [ ]  버그 수정
> * [ ]  코드 개선
> * [ ]  기타(아래에 자세한 내용을 기입해주세요)
> 
> ## 스크린샷 및 세부 내용 - 왜 해당 PR이 필요한지 자세하게 설명해주세요
> ![image](https://github.com/dh413/ThankYouFront2/assets/148740246/f241f418-2044-452e-9c19-311f252ad743)

> 땡큐에서 라디오버튼으로 되어있는 부분을 Search/Layout으로 처리 
> Search 공통컴포넌트 - 검색박스, Navigation 생성 -> 공통사용
> 검색키워드 (searchedKeywordState) recoil 추가   -> 공통사용

2024-05-29 07:17 UTC, daehyeongLee-aladin commented on src/app/(web)/search/layout.tsx
> +      <SearchText></SearchText>
children이 없다면 그냥 <SearchText /> 이런식으로 닫아주는게 좋을 거 같습니다!

2024-05-29 07:17 UTC, daehyeongLee-aladin commented on src/app/components/search/SearchNavigation.tsx
> +  // };
사용하지 않는 주석 코드는 제거해주세요~!

2024-05-29 07:17 UTC, daehyeongLee-aladin commented on src/app/components/search/SearchNavigation.tsx
> +          <li className="nav-item">
태그가 반복되는 부분을 map을 사용해서 코드를 줄이면 좋을 거 같습니다!

2024-05-29 07:17 UTC, daehyeongLee-aladin commented on src/app/components/search/SearchText.tsx
> +  };
handleKeyDown은 사용되고 있을까요? if문 안에 로직이 없어서요.

2024-05-29 07:17 UTC, daehyeongLee-aladin commented on src/app/components/search/SearchText.tsx
> +      <div className="input-group" style={{ width: "50%" }}>
w-50으로 하지 않고 inline style을 따로 두신 이유가 있을까요?

2024-05-29 07:33 UTC, dh413 commented on src/app/components/search/SearchText.tsx
> +      <div className="input-group" style={{ width: "50%" }}>
<div className="input-group" style={{ width: "50%" }}>
      ->
      <div className="w-50">
      으로 처리하면 버튼이 바닥으로 내려와서 인라인스타일로 처리했어요

2024-05-29 07:34 UTC, dh413 commented on src/app/components/search/SearchText.tsx
> +  };
나중에 쓰려고 주석처리 했습니다

2024-05-29 08:45 UTC, aladin-subin requested changes

2024-05-29 08:45 UTC, aladin-subin commented on src/app/(web)/search/layout.tsx
> +// /search/layout.tsx
주석 제거해주세요

2024-05-29 08:45 UTC, aladin-subin commented on src/app/(web)/search/layout.tsx
> +    <div>
스타일 적으로 감싸질 필요가 없다면 굳이 div 사용하지 않고 React.Fragment 사용하면 좋을 것 같습니다.

2024-05-29 08:45 UTC, aladin-subin commented on src/app/(web)/search/layout.tsx
> +      <SearchText></SearchText>
같은 의견입니다.

2024-05-29 08:45 UTC, aladin-subin commented on src/app/components/search/SearchNavigation.tsx
> +  // };
같은 의견입니다.

2024-05-29 08:45 UTC, aladin-subin commented on src/app/components/search/SearchNavigation.tsx
> +                path === "/search/customer" ? "text-primary" : ""
path 상수화해서 따로 관리해주세요.

2024-05-29 08:45 UTC, aladin-subin commented on src/app/components/search/SearchNavigation.tsx
> +          <li className="nav-item">
같은 의견입니다.

2024-05-29 08:45 UTC, aladin-subin commented on src/app/components/search/SearchNavigation.tsx
모든 path 다 상수화하여 관리해주세요.

2024-05-29 08:45 UTC, aladin-subin commented on src/app/components/search/SearchText.tsx
> +    useRecoilState(searchedKeywordState);
recoil 사용하시는 이유가 뭔가요?

2024-05-29 08:45 UTC, aladin-subin commented on src/app/recoil/search/index.ts
> +});
꼭 사용해야하는건지 이유를 생각해보시면 좋을 것 같습니다!
"왜" 사용하셨는지에 대해 생각해보시고, 사용하지 않는다면 어떻게 구현할지에 대해서도 고민해보시면 좋을 것 같습니다~!

2024-05-29 08:49 UTC, daehyeongLee-aladin commented on src/app/components/search/SearchText.tsx
> +  };
코드는 사용할 때 넣어주시면 좋을 거 같습니다!

2024-05-29 12:24 UTC, dh413 commented on src/app/(web)/search/layout.tsx
> +      <SearchText></SearchText>
단일태그 + children 제거했습니다

2024-05-29 12:33 UTC, dh413 commented on src/app/components/search/SearchNavigation.tsx
> +  // };
주의하겠습니다

2024-05-29 12:34 UTC, dh413 commented on src/app/components/search/SearchNavigation.tsx
> +          <li className="nav-item">
처리했습니다~

2024-05-29 12:36 UTC, dh413 commented on src/app/components/search/SearchText.tsx
> +  };
처리했습니다!

2024-05-29 12:37 UTC, dh413 commented on src/app/(web)/search/layout.tsx
> +// /search/layout.tsx
처리했습니다!

2024-05-29 12:39 UTC, dh413 commented on src/app/(web)/search/layout.tsx
> +    <div>
<></>
<Fragment>
</Fragment>

의미 없는 div가 추가되는 걸 막기 위해 쓰는군요 

처리했습니다!

2024-05-29 12:46 UTC, dh413 commented on src/app/components/search/SearchNavigation.tsx
@/constants/navItems 로 처리했습니다~

2024-05-29 12:50 UTC, dh413 commented on src/app/components/search/SearchText.tsx
> +    useRecoilState(searchedKeywordState);
navItem의 각각의 항목 페이지를 만들 예정인데 검색키워드는 공통이기 때문에  
recoil searchedKeywordState 를 이용해서 처리하려고 했는데 useRouter 으로 넘겨주면 될 것 같습니다.
사번같은 개인정보만 recoil로 넘겨주겠습니다.

2024-05-30 00:02 UTC, daehyeongLee-aladin commented on src/app/components/search/SearchText.tsx
> +      <div className="input-group" style={{ width: "50%" }}>
bootstrap과 인라인스타일을 혼재해서 사용하는게 어색해보입니다. 버튼이 바닥으로 내려가는 이유를 찾아서 수정하시는 게 좋을 것 같아요!

2024-05-30 00:09 UTC, aladin-subin requested changes
eslint, prettier 설정해주세요

2024-05-30 00:09 UTC, aladin-subin commented on src/app/(web)/layout.tsx
> +import Footer from "@/components/Footer";
공통된 컴포넌트라면 common과 같은 디렉토리에 묶어두는것이 좋을 것 같습니다.

2024-05-30 00:09 UTC, aladin-subin commented on src/app/(web)/search/layout.tsx
> +  );
layout인데 children은 어디에있나요?

2024-05-30 00:09 UTC, aladin-subin commented on src/components/login/LoginForm.tsx
>              router.push("/main");
path 상수로 관리해주세요

2024-05-30 00:09 UTC, aladin-subin commented on src/components/login/LoginForm.tsx
>              Cookies.set("user", JSON.stringify(result.data), { expires: 7 });
cookie key 상수로 관리해주세요

2024-05-30 00:09 UTC, aladin-subin commented on src/components/search/SearchText.tsx
> +  const [searchedKeyword, setSearchedKeyword] = useState("");
type 넣어주세요

2024-05-30 00:09 UTC, aladin-subin commented on src/constants/navItems.ts
파일명 navItems 보다 navigation이나 route 등의 이름이 더 좋을 것 같습니다.

2024-06-03 05:01 UTC, closed without merging